import './app.css';
import { Poppins } from 'next/font/google';
import Header from '@/component/layout/Header';

const inter = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin-ext'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
